name: hive_flutter
description: Extension for Hive. Makes it easier to use Hive in Flutter apps.
version: 2.0.0
homepage: https://github.com/hivedb/hive/tree/master/hive_flutter
documentation: https://docs.hivedb.dev/

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive:
    git:
      url: https://github.com/ExploreLtd/hive.git
      ref: main
  path_provider: ^2.1.5
  path: ^1.9.1

dev_dependencies:
  test: ^1.26.3
  lints: ^6.0.0
  mockito: ^5.5.0
  build_runner: any
